# Generated by Django 4.1.7 on 2023-03-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('ruble_cost', models.IntegerField()),
                ('dollar_cost', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passports.country')),
            ],
        ),
    ]
